------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">1.- ✍ Introducción.</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [1]:
# importar numpy con alias np
import numpy as np

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">2.- ✍ Funciones matemáticas y constantes</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [2]:
np.pi

3.141592653589793

In [3]:
np.e

2.718281828459045

In [4]:
np.log(10)

2.302585092994046

In [5]:
# coeficiente de correlación de Pearson
x = np.array([
    [1, 2, 3, 4, 5, 6, 8, 12, 11, 19],
    [7, 8, 9, 10, 11, 12, 13 ,14 ,15 ,16]
])
np.corrcoef(x)

array([[1.       , 0.9361986],
       [0.9361986, 1.       ]])

In [6]:
# media aritmética
np.mean(x)

9.3

In [7]:
# suma acumulada de los valores del array
np.cumsum(x)

array([  1,   3,   6,  10,  15,  21,  29,  41,  52,  71,  78,  86,  95,
       105, 116, 128, 141, 155, 170, 186], dtype=int32)

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">3.- ✍ Generación de array-s y alguna operación matemática</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [8]:
# Generar array
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [9]:
# Tipo de dato
a = np.array([1, 2, 3.0, 7.67])
print(a.dtype)

float64


In [10]:
# Generar array de tipo flotante
np.array([1, 2, 3, 9, 13], dtype=float)

array([ 1.,  2.,  3.,  9., 13.])

In [11]:
# De tipo complejo
np.array([1, 2, 3, 4 , 5], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [12]:
a

array([1.  , 2.  , 3.  , 7.67])

In [13]:
# conversión a tipo entero
a.astype(int)

array([1, 2, 3, 7])

In [14]:
# un nuevo array de forma y tipo dados, sin inicializar las entradas.
s = np.empty((3,3))
print (s)
s.shape

[[0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 8.0038635e-321]
 [1.0609979e-311 1.0609979e-311 0.0000000e+000]]


(3, 3)

In [15]:
X, Y = 5, 5
print (np.empty(25))
# matriz de 5x5 sin inicializar valores
j = np.empty(25).reshape(X, Y)
# matrices de 5x5 con valores aleatorios
k = np.random.rand(25).reshape(X, Y)
l = np.random.rand(25).reshape(X, Y)
j
k
l


[1.06116998e-311 7.16395186e-322 0.00000000e+000 0.00000000e+000
 1.89146896e-307 1.16095484e-028 2.96977369e+222 1.96086580e+243
 4.19334286e+228 9.62881650e+199 1.09745563e+248 7.26611031e+223
 3.71326426e+161 6.10941611e+223 1.10663757e+136 5.28595592e-085
 2.93625480e-062 1.75300433e+243 9.24896136e+135 4.24819624e+180
 6.48224637e+170 3.67145870e+228 2.72831122e-057 9.79107193e-307
 3.33509775e-317]


array([[0.84102878, 0.55493369, 0.68275375, 0.95139343, 0.95149794],
       [0.69462185, 0.91293166, 0.49673974, 0.28924694, 0.80693621],
       [0.62862672, 0.06421554, 0.27895604, 0.85629373, 0.97518042],
       [0.71449938, 0.44926121, 0.57572339, 0.87764572, 0.29499764],
       [0.01980073, 0.01364035, 0.42919767, 0.54050691, 0.57964489]])

In [16]:
# Suma de dos arrays
j = j + l
print (j)
# Multiplicación de dos arrays
j = j * l
print (j)

[[8.41028783e-001 5.54933687e-001 6.82753753e-001 9.51393429e-001
  9.51497937e-001]
 [6.94621851e-001 2.96977369e+222 1.96086580e+243 4.19334286e+228
  9.62881650e+199]
 [1.09745563e+248 7.26611031e+223 3.71326426e+161 6.10941611e+223
  1.10663757e+136]
 [7.14499379e-001 4.49261210e-001 1.75300433e+243 9.24896136e+135
  4.24819624e+180]
 [6.48224637e+170 3.67145870e+228 4.29197673e-001 5.40506907e-001
  5.79644893e-001]]
[[7.07329413e-001 3.07951397e-001 4.66152688e-001 9.05149458e-001
  9.05348324e-001]
 [4.82499516e-001 2.71120043e+222 9.74039958e+242 1.21291161e+228
  7.76984068e+199]
 [6.89889931e+247 4.66597206e+222 1.03583749e+161 5.23145473e+223
  1.07917130e+136]
 [5.10509363e-001 2.01835635e-001 1.00924559e+243 8.11731131e+135
  1.25320787e+180]
 [1.28353201e+169 5.00799640e+226 1.84210643e-001 2.92147716e-001
  3.35988202e-001]]


------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">4.- ✍ Indexación de Array-s y búsqueda de elementos</h3><br>
------------------------------------------------------------------------------------------------------<br>

In [17]:
# generar array
z = np.array([
    [1, 2, 3, 4, 5, 6, 8, 12, 11, 19],
    [7, 8, 9, 10, 11, 12, 13 ,14 ,15 ,16]
])
print (z.shape)

(2, 10)


In [18]:
# segunda fila
z[1]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [19]:
# corte entre segunda fila y segunda columna
z[1, 1]

8

In [20]:
# de la primera fila el corte con las columnas desde la 0 hasta la 2
z[0, 0:3]

array([1, 2, 3])

In [21]:
# corte de la primera fila con las columnas desde la primera hasta la última dando saltos de tres en tres
z[0, ::3]

array([ 1,  4,  8, 19])

In [22]:
# penúltima posición de la segunda fila
z[1, -2]

15

------------------------------------------------------------------------------------------------------<br>
<h2 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">5. Generar array-s</h2>

* A partir de array-s generados: `array`, `copy`
* 1 y 0: `empty`, `eye`, `ones`, `zeros`, `*_like`
* Rangos: `arange`, `linspace`, `logspace`, `meshgrid`
* Aleatorios: `rand`, `randn`

------------------------------------------------------------------------------------------------------<br>



In [23]:
# matriz identidad de 3x3
np.identity(3).astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [24]:
# saber diemensión de la matriz de la celda anterior
_.shape

(3, 3)

In [25]:
# matriz de unos
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [26]:
# matriz de ceros
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [27]:
# matriz identidad de 2x2
identidad = np.identity(2)
identidad

array([[1., 0.],
       [0., 1.]])

In [28]:
identidad.shape

(2, 2)

In [29]:
# matriz de unos con la dimensión de la matriz identidad
np.ones(identidad.shape)

array([[1., 1.],
       [1., 1.]])

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">6.- ✍ Rangos.</h3><br>

* linspace(start, stop, num=50)
* meshgrid 

------------------------------------------------------------------------------------------------------<br>


In [30]:
# vector del 0 al 10 separarado proporcionalmente en 5 rangos. Parecido al meshgrid
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">7.- ✍ Más operaciones con Array-s.</h3><br>

* Funciones matemáticas: `sin`, `cos`, `sqrt`, `exp`, ...
* Operadores lógicos: `<`, `~`, ...
* Funciones lógicas: `all`, `any`, `isnan`, `allclose`, ...

------------------------------------------------------------------------------------------------------<br>


In [31]:
# array del 0 al 8 de uno en uno
a = np.arange(3*3)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
# del 3 al 6 de uno en uno en coma flotante
a = np.arange(3., 7.)
a

array([3., 4., 5., 6.])

In [33]:
# array del 0 al 6 de uno en uno y dimensión de 2x3
a = np.arange(2 * 3).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [34]:
# raíz cuadrada de una matriz
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [35]:
# números complejos
np.arange(-3, 3).astype(complex)

array([-3.+0.j, -2.+0.j, -1.+0.j,  0.+0.j,  1.+0.j,  2.+0.j])

In [36]:
# generación de 2 vectores
a = np.arange(-1, 8)
b = np.zeros(9).astype(int)
a, b

(array([-1,  0,  1,  2,  3,  4,  5,  6,  7]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [37]:
# comparación booleana
a < b

array([ True, False, False, False, False, False, False, False, False])

In [38]:
# si se cumple la condición en alguna de las posiciones es True
np.any(a < b)

True

In [39]:
# si se cumple la condición en todas las posiciones es True
np.all(a < b)

False

<h3>👏👏👏 You guys rock !!!</h3>